---
title: "AT4BR_Exercises_6_Maria_Koziarz_10.04"
format: html
editor: visual
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(dplyr)
library(tidyr)
```

#### 1) Load the “iris” dataset.

```{r}
data("iris")

paged_table(iris)
```

#### 2) Transform it to longer

```{r}
iris_long<- iris %>%
  tidyr::pivot_longer(cols= -Species, names_to = "Trait", values_to = "Size")

print(iris_long)
```

#### 3) Answer the following questions:

-   What is the **mean** length and width of the sepal and petal of each species?

```{r}
iris_summary<- iris_long %>%
  group_by(Species, Trait)%>%
  summarise(MeanSize = mean(Size))
print(iris_summary)
```

-   What is the **largest** and **widest**, **petal** and **sepal**, of   **virginica** and **versicolor** species?

```{r}
iris_ranking<- iris_long %>%
  dplyr::filter(Species %in% c("virginica", "versicolor")) %>%
  dplyr::group_by(Species, Trait) %>%
  dplyr::summarise(max = max(Size))

  
print(iris_ranking)  
```

-    For each species, for **sepal** and **petal, width** and **length**, how many observations are above the mean?

```{r}
above_mean<- iris_long %>%
  dplyr::left_join(iris_summary, by=c('Species', 'Trait'))%>%
  dplyr::filter(Size > MeanSize)%>%
  dplyr::group_by(Species,Trait)%>%
  dplyr::summarise(aboveMean = n())

  

print(above_mean)
```
